### ISSUE TITLE
ubuntu excluded, not using platform_family

### ISSUE THREAD

**Issue by FredrikWendt** [sensu-plugins/sensu-plugins-cpu-checks#65]
tl;dr: Suggest changing `platform` to `platform_family`.

After adding this asset to a Sensu Backend, using `sensuctl asset add sensu-plugins/sensu-plugins-cpu-checks --rename sensu-plugins-cpu-checks`, the current 4.0.0 release shows this Bonsai metadata (`sensuctl asset list --format=yaml`):
```
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.name: sensu-plugins-cpu-checks
    io.sensu.bonsai.namespace: sensu-plugins
    io.sensu.bonsai.tags: ruby-runtime-2.4.4
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.version: 4.0.0
  name: sensu-plugins-cpu-checks
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    - entity.system.platform == 'debian'
    headers: null
    sha512: da5a183ad1a1f76962561eed659c6184b3e5d6a412432e1ccb4297cce123c41f9a8bb4fdb9ab19663aada978ea862ab2bd5f00bc91e4769ddd87543f5662b3af
    url: https://assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_debian_linux_amd64.tar.gz
```
(I removed rhel and alpine sections.)

This prevents the asset-managers in sensu agents running on Ubuntu from fetching this asset when running checks. I don't think exluding Ubuntu is intentional?

Thus I suggest changing the metadata from `platform` to `platform_family`, and quickly release a 4.0.1.
