### ISSUE TITLE
Bonsai debian9 filter definition is too broad

### ISSUE THREAD

**Issue by nixwiz** [sensu-plugins/sensu-plugins-cpu-checks#80]
The filters debian 9 are too broad, either remove or add debian platform_family and version to filter

```
- platform: "debian9"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_debian9_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
```
